class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzip2'
        self.TarMirrorCommand = 'tar2'
        self.ZipMirrorCommand = 'zip2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cnlall2'
        self.ListCommand = 'list2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stat'
        self.HelpCommand = 'hlp2'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest2'
        self.CloneCommand = 'clone2'
        self.CountCommand = 'count2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del2'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'
        self.GDTOTCommand = 'gdtot'

BotCommands = _BotCommands()
